language: node_js

node_js:
  - 7

install:
  - npm install --no-optional

script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run deploy

notifications:
  email:
    - entova@mondora.com