language: node_js

node_js:
  - 7

install:
  - npm install --no-optional
  - npm install --dev

script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run config

deploy:
  - provider: s3
    bucket: "entova.it"
    local_dir: build
    skip_cleanup: true
    region: eu-west-1
    endpoint: entova.it.s3-website.eu-central-1.amazonaws.com
  - provider: s3
    bucket: "www.entova.it"
    local_dir: build
    skip_cleanup: true
    region: eu-west-1
    endpoint: www.entova.it.s3-website.eu-central-1.amazonaws.com

notifications:
  email:
    - entova@mondora.com